"""user update for reset password

Revision ID: 0f4479c7efe7
Revises: 0913c04da758
Create Date: 2025-05-11 13:49:55.581949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4479c7efe7'
down_revision = '0913c04da758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiry')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
