"""Add is_suspended to restaurant

Revision ID: 495772be28e8
Revises: manual_add_category
Create Date: 2025-05-15 18:02:13.900058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495772be28e8'
down_revision = 'manual_add_category'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curier')
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('working_hours', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('working_hours')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('description')
        batch_op.drop_column('is_suspended')

    op.create_table('curier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
